[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# WIP
# [[patches]]
# [patches.pattern]
# target = "game.lua"
# pattern = 'G.load_shop_booster = nil'
# position = "after"
# payload = """
# elseif G.GAME.pool_flags.twbl_cursed_boosters then 
#     twitch_cursed_boosters_setup_shop()
# """
# match_indent = true

# [[patches]]
# [patches.pattern]
# target = "card.lua"
# pattern = '''function Card:click()'''
# position = "after"
# payload = '''
# if self.ability and self.ability.twbl_state_prevent_action then return end
# '''
# match_indent = true
# overwrite = false
