-- Chat can vote which pair of variables need to balance:
-- Cruel boss

-- Ante
-- Money
-- Hands
-- Discards
-- Hand size
-- Jokers slots
-- Consumables slots
-- Jokers count
-- Consumables count
-- Most often card
-- Most played hand level (Random hand?)
-- Amount of different hands played
