[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'function Card:update(dt)'
position = "after"
payload = """ """
match_indent = true

# WIP
# [[patches]]
# [patches.pattern]
# target = "card.lua"
# pattern = 'function Card:update(dt)'
# position = "after"
# payload = """
# if self.ability then
#     if self.ability.twbl_fee and not self.children.twbl_fee_particles then
#         self.children.twbl_fee_particles = Particles(0, 0, 0, 0, {
#             timer = 0.03,
#             scale = 0.2,
#             speed = 1,
#             lifespan = 0.5,
#             attach = self,
#             colours = { G.C.ORANGE },
#             fill = true,
#         })
#         self.children.twbl_fee_particles.static_rotation = true
#         self.children.twbl_fee_particles:set_role({
#             role_type = "Minor",
#             xy_bond = "Strong",
#             r_bond = "Strong",
#             major = self,
#         })
#     elseif not self.ability.twbl_fee and self.children.twbl_fee_particles then
#         local emitter = self.children.twbl_fee_particles
#         self.children.twbl_fee_particles = nil
#         emitter:fade(0.2, 1)
#         G.E_MANAGER:add_event(Event({
# 			trigger = "after",
# 			delay = 0.2,
# 			blocking = false,
# 			blockable = false,
# 			func = function()
#                 emitter:remove()
# 				return true
# 			end,
# 		}))
#     end
# end
# """
# match_indent = true
