[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = 'G.FUNCS.draw_from_discard_to_deck()'
position = "after"
payload = """
if G.GAME.blind.name == TW_BL.BLINDS.get_key("washer") then twbl_washer_wash_cards() end
"""
match_indent = true
