[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = 'function end_round()'
position = "after"
payload = """
TW_BL.G.clock_block = true
"""
match_indent = true
