[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for k, v in ipairs(scoring_hand) do v.ability.perma_debuff = true end"
position = "after"
payload = '''
elseif G.GAME.blind.name == TW_BL.BLINDS.get_key("trash_can") then
    blind_trash_can_remove_scored_cards(scoring_hand)
'''
match_indent = true
