[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'function Game:update_shop(dt)'
position = "after"
payload = """
if TW_BL.G.greed_no_shop and pseudorandom(pseudoseed("twbl_greed_skip_shop")) > 0.8 then
  TW_BL.G.greed_no_shop = nil
  return Game:update_blind_select(dt)
end
"""
match_indent = true
