[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# On booster pack open
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """G.E_MANAGER:add_event(Event({trigger = 'after', delay = 1.3*math.sqrt(G.SETTINGS.GAMESPEED), blockable = false, blocking = false, func = function()"""
position = "after"
payload = """
if self.ability.set == "Booster" and self.ability.twbl_chat_booster then
    G.E_MANAGER:add_event(Event({
        trigger = "immediate",
        blockable = false, blocking = false,
        func = function()
            TW_BL.STICKERS.get('chat_booster'):__on_booster_open(self)
            return true
        end,
    }))
end
"""
match_indent = true
times = 1

# On booster pack skip
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = 'G.FUNCS.end_consumeable(e)'
position = "before"
payload = """
if TW_BL.G.state_sticker_chat_booster and TW_BL.G.state_sticker_chat_booster.use and TW_BL.STICKERS.get('chat_booster'):__use() then return end
"""
match_indent = true

# On usage of consumable on booster pack
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = 'G.GAME.pack_choices = G.GAME.pack_choices - 1'
position = "after"
payload = """
elseif TW_BL.G.state_sticker_chat_booster and TW_BL.G.state_sticker_chat_booster.use and TW_BL.STICKERS.get('chat_booster'):__use() then
"""
match_indent = true


# On booster pack exit
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = 'G.FUNCS.end_consumeable = function(e, delayfac)'
position = "after"
payload = """
if G.booster_pack and TW_BL.G.state_sticker_chat_booster then
    TW_BL.STICKERS.get('chat_booster'):__on_booster_exit()
end
"""
match_indent = true

# Apply sticker on booster pack in shop
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''G.shop_booster:emplace(card)'''
position = "after"
payload = '''
TW_BL.STICKERS.get('chat_booster'):__naturally_apply(card, card.config.center, G.shop_booster)
'''
match_indent = true
overwrite = false

# Apply sticker on booster pack on create_card
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if card.ability.consumeable and not skip_materialize then card:start_materialize() end'''
position = "after"
payload = '''
TW_BL.STICKERS.get('chat_booster'):__naturally_apply(card, card.config.center, card.area)
'''
match_indent = true
overwrite = false

# Apply sticker on booster pack if created by skip tag
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.use_card = function(e, mute, nosave)'''
position = "after"
payload = '''
TW_BL.STICKERS.get('chat_booster'):__naturally_apply(e.config.ref_table, e.config.ref_table.config.center, e.config.ref_table.area)
'''
match_indent = true
overwrite = false
